migrations/1596492986396-add-redditnames-unique-index.js, web/routes/verification.js
ORM-level logic enforcement is good. This will prevent duplicate entries from ever being introduced to the `redditAccounts` collection. Also fixes a `// TODO` which is good for my sanity.
=> Add unique index for reddit links

migrations/1596302630862-add-guildid-to-redditaccounts.js
For some reason I thought it would be smart to drop a table in a migration. This would result in irreversible data loss if the database needed to be migrated down for whatever reason.
We're still in very early development at this point and store very little data that matters, but this was still awful practice and it baffles me that anyone lets me work on internet systems.
=> Don't needlessly drop tables from migrations

bot/commands/debug.js
since the prod app is owned by a team, https://github.com/Geo1088/yuuko#49 prevents anyone from using the debug command. Needs a fix in yuuko, but this is a temporary fix because I need this command now to troubleshoot a separate issue.
=> monkeypatch fix for debug command, Geo1088/yuuko#49

bot/commands/moderation/ban.js, bot/commands/moderation/unban.js, migrations/1597553486707-add-revokeDate-to-bans.js
Fixes a lingering issue with permabans I thought I got in #32, also adds an unban command and adds validation for ban `revokeDate` fields. This is used when a user is unbanned prematurely to indicate that the ban is no longer valid while keeping a record of when the ban was initially slated to expire.
=> Ban improvements

web/frontend/views/Verify.vue
`.account-box` styles were getting overridden by the default `.box` styles, not anymore
=> Center verification box properly

bot/commands/edit.js, bot/commands/misc/pick.js, bot/commands/say.js
The whole newline behavior is kinda wonky but I don't think it can be fixed within a command without over complicating things to extremes.
As it stands, I think it works just fine in normal use cases, provided you use the first line and don't skip right ahead. Visually it will look the same and providing support for people to start the block of text  on another line _after_ the arguments seems a bit overkill for a small bit of extra clarity when writing it.
=> Added say edit command

bot/commands/moderation/kick.js, bot/commands/moderation/warn.js, bot/commands/unverify.js, bot/commands/verify.js, bot/util/discord.js
Fixes an issue where a member wouldn't be accepted by commands even in ID/mention form.
=> Accept uncached members in parseGuildMember

bot/commands/misc/convert.js
Adds support for unit aliases, a defauly conversion value of 1, somewhat lenient whitespace, and "to" between units in arguments. Fixes #78. The following forms are now valid:
- `.convert usd jpy`
- `.convert 1ft "`
- `.convert 2 feet to inches`
The following aliases are supported:
- `'` to `ft`
- `foot` to `ft`
- `feet` to `ft`
- `"` to `in`
- `inch` to `in`
- `inches` to `in`
Should add more aliases than this but it's 4am, new issue for that.
The general form is now something like `[number?] [unit 1] [to?] [unit 2]` where only the two units are required and a space is not requred between the number and the first unit.
=> Better convert

bot/commands/debug.js, bot/commands/edit.js, bot/commands/misc/avatar.js, bot/commands/misc/convert.js, bot/commands/misc/joke.js, bot/commands/misc/pick.js, bot/commands/misc/roll.js, bot/commands/moderation/ban.js, bot/commands/moderation/kick.js, bot/commands/moderation/note.js, bot/commands/moderation/unban.js, bot/commands/moderation/warn.js, bot/commands/ping.js, bot/commands/reload.js, bot/commands/reminders/remind.js, bot/commands/say.js, bot/commands/unverify.js, bot/commands/verify.js, bot/commands/whois.js, bot/index.js
Added a helper function for triggering the help command from another command. Used this instead of ad-hoc help message sending to present a unified interface for command information.
This only applies to commands which have some sort of error condition when their arguments aren't fulfilled; commands like ping and joke don't take arguments, so nothing changed there.
Fixes #84.
=> Help info from commands

web/frontend/components/FilterEditorMultiple.vue
Without the children being assigned IDs when the component loads, trying to delete a preloaded element would always delete the first item in the child list since all IDs are `undefined` and not unique.
=> Fix issue with data loading for multi-selects

bot/commands/moderation/filteradd.js, bot/commands/moderation/filterdel.js, bot/events/messageCreate.js
Adds `.filteradd` and `.filterdel` which can be used to modify the filter rule from chat. They create/remove simple text match rules for message content.
Partially addresses #98. These will still need to be moved to subcommands of `.filter` when Yuuko supports subcommands.
=> Filter functions in commands

web/frontend/views/guild/MemberInfo.vue, web/routes/guilds.js
Bans are intentionally excluded from this PR because "deleting" a ban requires replicating the logic of the `.unban` command, and I want to unify that more properly. I don't want to do anything too complicated here before #94 - I have an idea for a better method of "deleting" things to maintain a more accurate user history in the case of mod error, but it's not practical until that gets done.
Fixes #103 for now. Will make a separate issue for adding unban functionality to the site.
=> Support deleting notes, warnings, kicks from website

bot/commands/whois.js
ZeroTsu had clickable URLs for Reddit accounts. A small annoyance while checking someone out in this bot was that we had to manually copy their username on Reddit to my browser, this fixes that I hope.
=> Added the full URL to the reddit username in .whois 

bot/commands/misc/convert.js, sample.config.js
- Updated .convert command to use an API key. It must also use HTTP instead of HTTPS now, due to us using the free plan.
- Fixed the error message not specifying the conversion types properly.
- Added the necessary section for third-party APIs in our config sample.
=> Fixed the convert command

web/routes/discordAuth.js, web/routes/redditAuth.js
Fixes #113. Always checks to ensure that both the passed state and the stored state are present and returns early if not. Additionally copies some implementation details from the Discord auth process to the Reddit one, since Discord's had some recent changes that made it more robust. (In the future we'll use generic middleware so these and other OAuth providers can be handled consistently without duplicating code between two files.)
=> Fix state matching

bot/index.js, package.json, yarn.lock
Bumps Eris/Yuuko versions. Eris 0.15 introduces an option to disabling legacy handling of audit log reasons, which fixes a bug that prevented bans from going through with audit log reasons that contained special characters.
=> eris@0.15, yuuko@2.2

bot/util/discord.js
Eris 0.14 included a breaking change where some events that previously included user ID arguments now include a possibly uncached user/member object instead. This was not handled properly in #116 - I upgraded from Eris 0.13 straight to 0.15, and forgot to read the breaking change list from 0.14.
=> Handle Eris 0.14's new reaction user arg type

bot/events/rssFeeds.js
Bug was caused by an incorrect assumption about Reddit's RSS feeds - they have stickies at the top so the first item can't be trusted to be the latest. We now compare the timestamps of all items in the feed when processing; it's also now impossible to write a time back earlier than the one already present in the database. Also some other cleanup - standardized on `new Date()` rather than `Date.parse()` for date comparisons to keep things a bit simpler.
=> Fix RSS feeds

bot/events/rssFeeds.js
Use footer image instead of thumbnail for Reddit logo, include post URL as embed title link, display timestamp in `timestamp` field for relative date display, more robust URL checking for Reddit links that can be expanded to other services in the future if we want.
Not sure what's up with the `thumbnail` field but it doesn't seem to display nicely - this should fix title text being shoved all the way to the left like [that](https://discord.com/channels/267799767843602452/283592211986382849/855499495198425108).
=> Change up RSS embeds

bot/events/bans.js, bot/events/reactionRoles.js, bot/events/reminders.js, bot/events/rssFeeds.js
Having a function call itself after execution ensures that it won't be queued until after it's done, which is nice, but it relies on the function getting that far in order to execute itself again. If there are errors in execution, it will end the loop, which is a bad time. This PR swaps these things to use `setInterval` instead in order to ensure they'll keep happening even if one run fails. It also adds catch-all logging and a check for the client's connection state before trying to do things against the Discord API, which I have a feeling might be part of why things were breaking before.
=> Guard against periodic action failures

src/bot/events/rssFeeds.js
Fixes an issue with RSS feeds not being posted correctly. Naming variables is important.
=> Channel IDs don't have methods

src/bot/commands/moderation/ban.js, src/bot/util/discord.js
Adds support for Discord's new `<t:TIMESTAMP[:FORMAT]>` date/time formatting. Not currently supported on all platforms; don't merge until this shows up correctly everywhere.
=> Relative timestamps

src/bot/commands/reminders/remind.js, src/bot/commands/reminders/remindlist.js, src/bot/events/reminders.js, src/bot/util/discord.js
Reminders weren't using the date formatting methods initially but now they are, so they get the new fancy relative time display now.
=> Use timestamp formatting for reminders too

README.md, tsconfig.json
Ties the project to Node 12+. Fixes strange issues with roles not being returned from the API because of strange behavior with `--allowJs` but not `--checkJs` - see https://github.com/microsoft/TypeScript/issues/45251 for more detail.
=> Target explicit Node version

src/web/index.js, src/web/middleware/accessControl.js
Enables testing the frontend and the API on different origins in development. This will be necessary for a local test of the frontend and API together, since both their dev modes live on different ports and therefore different origins.
=> Allow cross-origin requests outside production

src/web/routes/channelAutomation.js, src/web/util.js
Doesn't totally remove `TEMP_guildID`, but does remove it from routes where it isn't necessary. The production bot is not public at the moment, so it's safe to assume that we're the only guild the bot is in, and therefore it's not necessary to explicitly check this.
=> Remove hardcode from generic auth check

src/web/middleware/accessControl.js
Adds handling for extra `Access-Control-*` headers to properly handle preflight requests outside production.
Ref https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
=> Add access control handling for preflight requests

src/bot/index.js
Makes sure we have access to message content (yuuko still doesn't support application commands) and guild members (since we still use `getAllUsers` for now, #76). In the future we can customize this to exclude intents we don't need, like probably typing events and stuff like that.
=> Specify intents explicitly

src/bot/index.js
Reverts r-anime/misato#182. Somehow specifying `Constants.Intents.all` doesn't give the `guildMembers` intent, so client construction errors out with `Error: Cannot request all members without guildMembers intent.`
=> Revert "Specify intents explicitly"

src/bot/commands/whois.js
Now we can see which mod added a note, warned, kicked or banned a user in the output from `.whois`. I also added a label for the link to the website.
Will look like this:
=> Add more details to .whois output

src/bot/commands/moderation/ban.js, src/bot/commands/whois.js
The URL shown by `.whois` now appears on the next line. Also fixed a spelling mistake.
It looks like this:
=> Minor improvements to text

src/bot/events/trackBoosters.js, src/bot/events/trackMembersLeaving.js
The bot will now log when a user stops boosting. If a user leaves while being a booster then it will log that they left and that they stopped boosting since the boost is removed automatically.
The messages will look like this:
=> Make bot log when a user stops boosting and when they leave

.github/workflows/ci.yml, .gitignore, package.json
The build output doesn't actually matter since we use `ts-node` in production, but making sure the project compiles is probably a good idea
=> Build Typescript as part of CI workflow

src/bot/events/messageCreate.js, src/bot/events/trackMembersLeaving.js, src/bot/events/verification.js
`<@id>` mention format doesn't prompt the client to fetch the user's information if it's not already cached. `<@!id>` does, so using it results in the actual name/nickname of the user showing up more of the time.
Discord lists `<@!id>` as "deprecated" and "should be handled like any other user mention" but... that's not what the client does. so that's cool. https://discord.com/developers/docs/reference#message-formatting
=> use <@!id> for join message mentions

.github/workflows/ci.yml
Updates `@actions/checkout` and `@actions/setup-node` to their latest major versions. Also sets up the workflow to read the node version from `.nvmrc` instead of always using 12 (! that version isn't even LTS anymore!)
=> Always use latest node for CI runs; update actions

src/bot/commands/ping.js
Repo URL is now fetched dynamically from the current environment's `origin` git remote, rather than being hardcoded into the command. Warnings are added for if the current commit or git remote can't be found. Output now includes a nudge towards the help command. The actual meaning of the time displayed is shown. Message formatting code has been restructured to be reasonable.
=> Ping command improvements

src/bot/events/rssFeeds.js
Fixes #217. Adds special handling for Nitter feeds in the RSS feed handler which posts them as Twitter links using normal Twitter embeds.
Nitter has multiple instances; the main one, https://nitter.net, seems to be somewhat slow, but they all work pretty much the same. To make a feed for the user, open up a nitter instance, find the user in the interface, then right-click the feed icon in the navbar and copy that link to use in the `createrssfeed` command.
=> Twitter feed support via Nitter

src/bot/commands/misc/convert.js
The command wasn't working when using lowercase temperature units before and this fixes that
=> Add unit aliases for temperature units

src/bot/commands/moderation/filteradd.js
Added a null check because the bot crashes if `existingRule` is null
=> Fix bug in .filteradd

package-lock.json, package.json
Upon starting with the current configuration, `npx` first needs to install `ts-node` as it is not installed during the container build process.  This makes the container take longer to start, and causes nginx to give a 502 error for that service's routes for several seconds.
By changing `ts-node` to a non-dev dependency, it will already exist in the container, letting it start much faster.
=> Update node-ts to be a runtime dependency

package-lock.json, package.json, src/bot/commands/misc/avatar.js, src/bot/commands/misc/convert.js, src/bot/commands/misc/defaultavatar.js, src/bot/commands/misc/joke.js, src/bot/commands/misc/pick.js, src/bot/commands/misc/roll.js, src/bot/commands/ping.js, src/bot/commands/reminders/remind.js, src/bot/index.js
i hate discord i hate discord i ha
=> Fix commands that send messages in DMs crashing the entire bot

src/bot/commands/moderation/ban.js, src/bot/commands/moderation/kick.js, src/bot/commands/whois.js, src/bot/events/rssFeeds.js, src/bot/util/discord.ts
Fixes #252. Kick/ban messages longer than 512 characters will appear cut off with an ellipsis in the audit log.
Adds a helper for truncating strings and adding an ellipsis if necessary. Cleans up some other areas where we do similar things as well.
=> Limit audit log reasons for kicks and bans to 512 characters
