r-anime/misato

- .gitignore
- bot/commands/joke.js
+ Added Joke command. 
* Fixed my useless gitignore addition
> Small commands

- .github/workflows/deploy.yml
- package.json
> Build+deploy stuff

- bot/commands/moderation/ban.js
- bot/commands/moderation/kick.js
- bot/commands/whois.js
- bot/events/bans.js
- bot/util/discord.js
- migrations/1596502200514-create-collection-bans.js
- migrations/1596507742549-create-collection-kicks.js
Enables leaving notes on kicks and bans, as well as specifying the duration of bans. Two new collections, `kicks` and `bans` respectively. Also introduces several helpers, including a time parsing function that will be useful for #3.
Still todo:
> Kick+ban notes, timed bans

- bot/commands/verify.js
- bot/events/reminders.js
- web/routes/discordAuth.js
- web/routes/redditAuth.js
Wording stuff and console log removals and stuff like that
> Misc fixes

- bot/events/verification.js
- bot/index.js
- sample.config.js
When a user joins the server, if they've already verified in the past, they will be given the verification role automatically. Fixes #25
> Reverify on rejoin

- bot/commands/moderation/ban.js
- bot/commands/moderation/kick.js
- bot/commands/whois.js
- bot/index.js
- bot/util/discord.js
- Support for parsing "me" as a user argument
- Support for parsing users that aren't members of the current guild
- Send notifications for kicks and bans ([examples](https://user-images.githubusercontent.com/4165301/90326538-6b166500-df57-11ea-8139-2b462fc37cc4.png))
> Command improvements

- bot/commands/moderation/ban.js
should fix a permaban issue encountered in the server
> don't write non-date values as ban expirationDates

- bot/commands/moderation/note.js
- bot/commands/moderation/warn.js
- bot/commands/whois.js
- migrations/1599940527568-create-collection-warnings.js
- migrations/1599941911368-create-collection-notes.js
Adds `.warn` and `.note` for issuing warnings and leaving user notes.
`.warn @User reason` will send the user a message with the reason and write the warning to the database. It will fail if the user can't receive DMs. Reason is optional.
`.note @User content` will save a private mod note in the database without notifying the user. Note content is required.
> Warnings and notes

- bot/commands/debug.js
- yarn.lock
Yuuko v2.0.1 fixes the issue with owner detection that I was complaining about, so the custom solution is no longer necessary. Fixes #35.
> Update yuuko and remove monkeypatch owner hack

- bot/commands/unverify.js
- migrations/1596302630862-add-guildid-to-redditaccounts.js
Oh god this is a mess I really need to put a structure around role ID settings soon.
> Unverify command

- bot/commands/moderation/note.js
- bot/commands/whois.js
- Users not in guild can be passed to some commands
- Whois can show users linked to a reddit account now
review later, am tired
> Allow passing more things to commands

- .github/workflows/deploy.yml
Fixes a warning message about deprecated github actions stuff.
> deploy: upgrade webfactory/ssh-agent to 0.4.1

- bot/commands/moderation/note.js
> Fix note command stupid error

- web/frontend/views/Verify.vue
> Move "Verify Accounts" button to top of page

- bot/index.js
Fixes more issues with `parseUser`/`parseGuildMember` but needs to be done better later, #76
> add getAllUsers for now

- web/frontend/App.vue
- web/frontend/router.js
- web/frontend/store.js
- web/frontend/views/Guild.vue
- web/frontend/views/guild/GuildMemberInfo.vue
- web/routes/guilds.js
- webpack.config.js
show username on member page, improvements to display flashing when page is loading, etc
Includes new API route /api/guilds/:guildID/members/:memberID/about for fetching Discord's info about a member. In the future should only fetch user data since that's all that's required to display their username though. Also need to work out some sort of more structured cache for the frontend so we can do parallel requests when the page is loading.
> Frontend UX improvements

- bot/commands/unverify.js
- bot/events/verification.js
- bot/index.js
- migrations/1608004537390-create-collection-verificationConfiguration.js
- sample.config.js
- web/frontend/views/guild/GuildInfo.vue
- web/routes/api.js
- web/routes/guilds.js
- web/routes/verification.js
- web/util.js
Finally, the web config concept is actually going somewhere 🎉
> Frontend config for verification role

- web/frontend/App.vue
- web/frontend/components/FilterEditorMultiple.vue
- web/frontend/views/Guild.vue
- web/frontend/views/Home.vue
> Misc ux improvements

- bot/commands/moderation/filter.js
eventually I'll do more with this
> Basic filter command that redirects to the website

- bot/commands/whois.js
Little mishap with git because I'm dumb, hence the 3 commits but this should fix the bug with underscores breaking .whois URLs.
> Who is improvement

- bot/commands/moderation/ban.js
- bot/commands/moderation/kick.js
Adds additional logging around kick/ban errors, and additional context to command feedback when the user has already been notified of the action that failed.
> Better messages and logging for ban/kick failures

- bot/commands/setstatus.js
> Add setstatus command

- web/routes/filters.js
insert "how many times do we have to teach you this lesson, old man" meme
> Never call response.end() without returning afterwards

- bot/events/rssFeeds.js
> Revert RSS frequency change from testing

- bot/events/bans.js
- migrations/1626966666740-add-unbannedAt-to-bans.js
Fixes #120. Bans now have an additional field that tracks when they were revoked by the bot. Additionally, "Unknown Ban" errors are handled by marking the ban as auto revoked.
> better-ban-handling

- bot/events/rssFeeds.js
> Publish RSS feed messages in news channels

- web/routes/channelAutomation.js
- web/util.js
Fixes #135. Also adds a note to another thing that will need fixing in a future Eris version.
> Fix member permission deprecation

- bot/commands/moderation/warn.js
- bot/events/bans.js
> Always record warnings

- .eslintrc.cjs
- package.json
- src/bot/util/formatting.js
- src/common/filters.js
- yarn.lock
Adds an eslint rule for checking imports, which should've been a part of #147. Fixes related issues introduced in #147 that prevented filters and Discord formatting functions from working, breaking lots of stuff.
> Fix imports

- .github/workflows/deploy.yml
Fixes a deploy issue introduced with #152
> No longer need to build frontend

- README.md
[fuck me dude](https://discord.com/channels/267799767843602452/700403512831377508/870444203979718766)
> Add note about required intents to README

- sample.config.js
- src/bot/commands/misc/convert.js
Switches away from the currency API we were using because it was causing problems. Fixes currency conversion failures caused by the API suddenly only accepting certain base currencies.
> Better currency api

- src/web/routes/redditAuth.js
Fixes #154. Makes Reddit avatars work again.
> Use raw_json for Reddit requests

- sample.config.js
- src/bot/events/messageCreate.js
Will break this out into a more proper logging feature with more events and configuration later probably.
> Add simple hardcoded logging for filtered messages

- README.md
The command should be `npx migrate up` and not `npx run migrate up`
> Change migrate command in README.md

- src/bot/commands/misc/convert.js
hi, here I added the validation of units for the use case of convert currency.
if the units received are not accepted, it throws an error.
> Add validations of accepted units in convertCurrency

- README.md
- src/bot/commands/whois.js
Hey, I added the user's discord username and discriminator along with their account age to the message generated by .whois
> Add more information to .whois output

- src/bot/events/rssFeeds.js
Re-fixes #134. #146 was dumb as hell
> Actually publish feed messages in news channels now

- src/bot/commands/reminders/remind.js
zerotsu used `%remindme`, this is consistent
> add remindme alias for mage

- src/bot/commands/whois.js
> Limit whois output to 2000 characters

- src/bot/events/verification.js
Logs users who joined. Fixes #22 
Looks like this:
> Server join logging

- sample.config.js
- src/bot/commands/whois.js
Used Ban Date - Expiration Date since it'll work for older bans too.
> Update sample.config and update .whois to include ban length

- src/bot/commands/whois.js
- src/bot/events/trackMembersLeaving.js
- src/bot/events/verification.js
I did this by removing the option to suppress pings on `messageCreate`. Leave logs seem to still have the issue
> Fix tags not appearing correctly on logs and whois

- .eslintrc.cjs
- package-lock.json
- package.json
- src/bot/util/discord.ts
> Convert Discord formatting utils to Typescript

- src/bot/commands/misc/convert.js
Fixes #193. Creating as a draft because I haven't actually tested this yet
> Update freecurrencyapi.net -> api.currencyapi.com

- src/bot/events/rssFeeds.js
Adds more logging to RSS stuff in the hopes that next time we have issues with duplicate posts we'll have more info to go off and try to figure out what's wrong
> Add more logging for RSS posting

- src/bot/events/messageDelete.js
- src/bot/events/trackMemberBans.js
I also added a try block in the message deletion log file because it seems to crash seemingly randomly when you choose to delete the messages of a user when manually banning
> Add ban logging

- src/bot/events/joinThreads.js
> Automatically join all visible threads
